V2: Project2.1.c Matrix.c Matrix.h List3.c List3.h Object.c Object.h IO.c IO.h
	gcc -o ecosystem Project2.2.c Object.c Matrix.c List3.c IO.c -lm -fopenmp -I.

L1: Project2.1.c Matrix.c Matrix.h List.c List.h Object.c Object.h IO.c IO.h
	gcc -o ecosystem Project2.1.c Object.c Matrix.c List.c IO.c -lm -fopenmp -I.

L2: Project2.1.c Matrix.c Matrix.h List2.c List2.h Object.c Object.h IO.c IO.h
	gcc -o ecosystem Project2.1.c Object.c Matrix.c List2.c IO.c -lm -fopenmp -I.

L3: Project2.1.c Matrix.c Matrix.h List3.c List3.h Object.c Object.h IO.c IO.h
	gcc -o ecosystem Project2.1.c Object.c Matrix.c List3.c IO.c -lm -fopenmp -I.